apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:UyZRsyV3WbTi4iv3aKdTmjec7CHHDPsc9vhnhIvRVL9tFwOcP0D4BQfTcVqVqqBOo9d2kNfehYn54wq8zykR0ZEazfDv8ZyQlAe2Vtr57URpFkGajnyuIYB3HMGMtxLL4wq0mRd706zHAhwWQDcmfiaOzlvRvgGBelS8dfCvObnJHLPfgLsp289C2e3f/SlYhqqgy5GzP+Zoeg1UB4hVRavV3fjjLg/QZPtpSOwyFNIop2rM,iv:CkcfOGj5UwwfpnhCdL1t9RBdVWhjuxiZEC61+0s+rVE=,tag:Q6ulDM7M7Aqjt98W8dpC2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTEdHbTBYQVlKMnJWMWl1
            U2hQWFUyYzhsTEdvYUlRcVpxZGRtckp0YVJNCkpkYnhQbFhMNXQwbEZoNlRFRzN4
            UTFvOEZTVXFkT0RJZmtTcU1DL1k0aVkKLS0tIEpCa1ZKcjdCSUUxcEhBcW9TY0Rt
            UEx5eHhteUVhMUVCaHN5NUVpUUFZbGMK7jh0XWh6432wQ3WzLl3pku5jcQH7dJtk
            nPmEKOfCfavRu/nNqDavIjcY1WJa+PppUYXDU/YPoI4WzF3AdxG8wA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TzNTNFEvaXpCdm9oc0JM
            eWNzUDFzM3RSYkQvd1JETEtFZ1Q1S25mSDJFCjIvc2VOb0ZVemFvcG0vWVZDZDlR
            NVhXMWRjajliTTgyZ1R1b0FSbThDSU0KLS0tIHUrbyt5VjZLQURyQUNwUy85ckRS
            aStWOFNETkFmTmlJSEpidFpERVY1aFUK8Ve+uJ6tWDKGouqFmTytM6gavt+EeNXy
            xR9twJuo1sFpD6lWWv/heSajixM38APV6dCu1imQanHrCXZTKt4QJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T08:31:49Z"
    mac: ENC[AES256_GCM,data:5DXFZqm7CyXcSJSlSpvA5otkdDwb0uXdij1XrS1nAfLqH9u2hjrifCCY/D+07o/dN8sdSO7NON2u0nie0QcKV0CEgxrxzi1RsaNfYOJxxlKrpqIDDJFP8tA9BTF6ifQ/Co96mj2m3DaA7IiPAh5+UL/OjuZqtYzPJ0tam3OSmks=,iv:kHmqov5EDDPe2whxBVuhJPgZ7u5mDQ1yW0wwgoeL8aY=,tag:/pbmgS8+bIFYQLA+NZOm0w==,type:str]
    version: 3.13.3
