apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: notebook
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:z6jdtr8OR/utAAJCbs01GVCaeiI=,iv:M0rOG8FNOns3wx2r+kzNfu1TwtqBItNpkL05PK7TKcI=,tag:AJMRzrfwoQCTpyHQTZI0yg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XAM7mwXElzCw3dpJu0FNr6KbsOsVonZIt0lHrNXAm+CqlMG7OnAEFA==,iv:+eMWyZFDP27CaMULsElH4RP5ww+0zG/gfywpiNsL854=,tag:IJCHEGWmDdYfk6+GaUuxrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY0o3RDlnaVZGaS9MNm1E
            MHg5dGRHNXJUY3hNaThaRUxMVlRRTHFTTno4CmFVT2pLTXdaeCtFc0t4aFMwb0t6
            TXZzY1A1R1gvU2psTUR6bGxhWmRtbEUKLS0tIENyd1EzSjZ1SVBpR205SkZJYUNF
            YzlqaUVpOTBDUjl6MGM1bjdHa01JSHMKiNmNCfZ+S71zk+W59uozinVZdTMgEchV
            5TdcJZrhWP6EAqRD8mx7DQcY63UcA8FOLpGA2dOlUH8ej+c9HvFCCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ektwNDNmQjdiY3JVN0E1
            a1BXMktiK2YrM2NVSEp2T0xtTklXQkV0RHdrClpuNVFpMmg4eUp6SHdRYVZCeWNV
            OE9GNlJPUm5pYlhIV0FaWTZMSVZPOTAKLS0tIEZXNDRlamFuWlZUOTJlTUFSZHoz
            blBveVY2RXpSOTRrdCtxZ3k5d21FeEEKs25qMy6aCaiqiwBXsqBmAurqXncBqqt/
            3jPT3oXeY7IKiMWN4CQFXq/c1vXpDmdLwZkex2duV8MAyRH267o0WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T14:21:57Z"
    mac: ENC[AES256_GCM,data:AH3KQMzYOmMSvoVQ6P/AYCmCiKGntu5AdMCAf93hjLZ3TVkkjVTakDclut5vE//s7rqCwx2DBKnf/yh6B5lDMPg8+xeMQ9hG0+ECHW+/CqDcUs0XgtTf0UhxujSbnynxXbc70+VwCkqERbsDa5cbmDikOhb8H7BEe8uhhxl2/BU=,iv:G1JEwZoRwsLhHWWfBPZyesqcHj/f1RR+swZ0Zems9kY=,tag:Dka5tDBHM8QhHA5VHhFsSg==,type:str]
    version: 3.13.3
