apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/gateway.yaml
  - applications/cloudflared.yaml
  - applications/cert-manager-issuers.yaml
  - applications/cnpg-operator.yaml
  - applications/barman-cloud.yaml
  - applications/kube-prometheus-stack.yaml
  - applications/kube-prometheus-stack-resources.yaml
  - applications/loki.yaml
  - applications/loki-resources.yaml
  - applications/k8s-monitoring.yaml
  - applications/notebook-api.yaml
  - applications/authentik-resources.yaml
  - applications/authentik.yaml
  - applications/argocd.yaml
