apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- digest: sha256:d84dcb7dd081de5e9697dbc8967146b6072174937d9de436deb384e5c7a34744
  name: ghcr.io/ivanpanev/notebook-api
  newName: ghcr.io/ivanpanev/notebook-api
  newTag: ad49ebe98107adad034bc594dbac15ed36c9a093
