apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:RTpVjXCk4zZmiaqkdnYaT8jstVZI+rFktXsg9lvgHA68G6a6UgSRoM4PyqjIZon4Y1zmEiE=,iv:cy3WAIoIg0Mtav9vPS9y+j81UZoyPBD6XV83zVMUkgo=,tag:gnza3Cqt++U9i4jE7IZESw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TFZTUVl1ZVE2VG11NlJG
            dUN0dzVzc2xxclZPQlVJNGZLNTU1R1c0T1dnCm5LUWhBM0NOa0JSaU5uMDBBV1Bj
            cHltNnN5MTg3ZHZuSEphSE5YTGhUZ2cKLS0tIGx2WUI5ZVd4RTIwWGhwMy81bWM0
            VGFiN2F2bHJHWDF5a3AvL2dITHRyVHMKLcqzwgyMmyLdkOJoBfstwC53VSsgHwcL
            6xezxa8Gcl8iRklHQ5RF6AoiaAbUvKq36wGLENRLqYc5azrwfaUsAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNUJkeHpCQ0JjR01mSG95
            SGg5VFZqRlNQbUgvemVaSCt3dm1KdE5xRnpVCkYwbnMreGFQRFBaLzFHNUxFbnRj
            cU5EdjJjZlB4N0xxdHIvZHZSMlQvQ28KLS0tIDdqWCtCUnN2d0dXQlBLNnEzODQv
            aEsyYjVyd3Bxekl3eVRlTGt2dzhsMjgK523/cb80FJx5onPdIMRrFw0RXMoCp3e+
            52BLZZvTIMwYMQFRY1MmNJhlm7B6xvrRyPvFzVIgRyUu70JJx1gn5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T08:31:01Z"
    mac: ENC[AES256_GCM,data:X92mSSdiRGSlnW8Heijb1Q1Du2nKDoYabTKTObjvHDsszN7kjVPutoHeuMGjVWQcumzJJzW0bB8JI9elXP9wicN/4CSnTYDT4dxYHbdfyPVe2PYGLTvoPZvefK4MHD1DeZIOGTnSssvFvvxKLOI8uOEb62sfTsKeZ4gmePd/d9g=,iv:udNeU3RohMiPA5qzLScMYESROr2IoJHgmE4WnHy1QJc=,tag:XI7H0RwVeCafCk4qQrgvUg==,type:str]
    version: 3.13.3
