apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7ID9f+ikL5u5SJXeAI/aq5kskxT1M2yWaCB4mO3QCsI3XfxZtoCZPtcIX2El/dJOCpXM0OTJuXfZPoN+IxxRpt94nw==,iv:aa1TgaV7aSzARvqBwbfG6HWPQhE0vDORWKwFPFazBgE=,tag:xFfWQCiwLJlDswkPYQmlOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1JFRkJYN3NYYUE0VGVp
            cUxHc25XOGlVOHZBOWVTcVRNRVMyOGtkR0V3Ck9wbTVaMnNQOFlVZVBBY2UxUW9E
            b0ZOY1JBR2hvaktPTEdhcEFhWTRHWXcKLS0tIFAxR2RZcG1hNUV0UHUzRVhIem5i
            dmxQZzRSQ1c3M2ZneDRxdDVoMmZKZWsKURqhupE0aDlZNI27Q3x8LgJGdjzTDa1c
            EK2+W3bYJG5IAt9BvTzGcwIne4IvTfhTK4timHTFSRVkBlXy6dp/Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMXVQSTRzOFpnV1lRdy9u
            ZWJWY2hrb2d2cGFJSTVTMElpWjNYQlovMlVBCnZPayt4VTBjVERWSGwzNWhJd2xN
            c1BQZ1lXV08rcTYybTEyeG9iWUtjbncKLS0tIDNZTWR4TnV6eUhqT0hRd3p3ZFFk
            L015d3ZuWWxXWThOTUU4OHZjM0JyMUUKSZdVfrfhj22dpooS3f/CDjQPmtRzfskl
            tpsnlmqxrmr47LXE32YBQ8LwVC5OWqIgLdiRpLXP0/fcd1wSJ3JGxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T16:03:25Z"
    mac: ENC[AES256_GCM,data:FunbJrrMwFVSFgpFwLWTkhW3+1UVUVtFdwB7i4FbxbpkxPKjSJTh00RWZ/EvmGyfNk/uDThR3AoBsLejfYdL5H4rfd8s5b+Ffy6yXcTSllSLoGx03Nrr5DmJsUbtFsNWY84YODF+qwIcM9t7k4HwlI0BNuB4sI1O2fjwC1xIxH0=,iv:MTo4LwDv0pFYoi9ebHT+2S70eK+TH74u6IAdgZBARwQ=,tag:OVcQ43TRBCD68vXSbA9ynA==,type:str]
    version: 3.13.3
