apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3
    namespace: authentik
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:NtxPeCgPApbdokAMP66qDDImIN4=,iv:1CNPxq3SRdX+tlT90I/4sUD4WTXNe5/QtKDs0ma/p2U=,tag:LlqXe/J8KROZpgCPCgn86g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:TZ80g/WKeJdZYbK0aU4evbraOUrRnqIwoOjxh6KWvO9BY41C5Cyc4Q==,iv:pw1BfY/9PZayqaDTVEP1kJNH6HXo7s6fAlrudsx2AMs=,tag:h4kIIX6LocP+Qb96P1yTxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcGJGd3hLRUo5UkpWRXRh
            YVZsM2Uwb0J4K3RURWg2RFpXdVY2ejhrRkM4Cks3Q3hCbzMzM0ttYlVYRFRsK3M5
            RHBTbXV3djkybDZ0c3UwMnBaYUZoZ3cKLS0tIFpHL2hGS3Ezd0lyRUFGdytaUlJ6
            ajdWVTl4L0FhSEk3TFdXb2RaU0RjZnMKQVY6tABqr4Or8uqhUAgCG3ypOBNZuHbK
            OVDkTpcKejnsfYvWN0KPxl/BEIVxE4SNnFlHZ0t2+lRkYf/nTTWP4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbHdUdUQzMGFTS3ZwVVF0
            UGMzdDc2WFp1cEtaMFdVUW0zc0Nkd0dWclNvCjN1eW14WUx4WHBrOUczQnZGS0tQ
            ZXM0U2JHREF3WTZCOTFRdG1rczAvUzAKLS0tIGJ5T1RMeVJ0WnlWbGxVdFBXaU42
            Q2c4MmVNVFZwYkpRbjI1YWhFcjVoQ0UKQVvpCOIh+Epbsq0J1KPMt+QwbJzyt5/q
            4cP8oLdN5FEhFmSus14Y2w4cThJDa0/5yFdbCvOv5V2TtiqPJN3D8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T15:49:26Z"
    mac: ENC[AES256_GCM,data:phzrS3BV/POBj1dmY2rl0O2iqKZPwjkLzG7YdCzk40sn9Nq3oNnPemmE5FqfcNvpkEsAeCghjuJbi1qMxVpyCuP1Brzk54gJnGNHG934JDKvPscX73GzWB3J6WDNwoFPTkbTZG9ERppIZglxRPMU2R/LpQ5uNhK+ejaNMVFpEWo=,iv:hWuCdsnIwIzluH96DVClMGCSjyLUnQTf50QTJftr//E=,tag:mxrMyc4yhlDXoNPAbox2hQ==,type:str]
    version: 3.13.3
