apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: authentik
  namespace: authentik
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://ivp-cnpg/authentik
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: cnpg-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
      jobs: 2
  instanceSidecarConfiguration:
    env:
      - name: AWS_REGION
        value: fsn1
      - name: AWS_EC2_METADATA_DISABLED
        value: "true"
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
