apiVersion: v1
kind: Secret
metadata:
    name: loki-s3
    namespace: loki
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PmuVKuZ4gBInlvHU5nU0p7BsorU=,iv:OoPWF7noYnUSSwFgm0H2AWVMcJ/Q6dlcF/lB2VqDVeI=,tag:CYvPBoxSHTvtvT1aB70h5g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pZBZGZzXgjzkTMRW2kpYLKcJl1yMCyBNsLlfPqeqbEFoWGI3pXFUAw==,iv:rlDvHRrwl+DMOP2p5vyc0ATMA9uRMp0OtMFgC3mIsFE=,tag:xqBxna2axU/nZgpL46Ao4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSlZwWHBBZGlMQzYwekRy
            N3RsSDBYNElqQStKb3JhbXhocWRtR2dOcmw4CmJwOCtqZElyNHpvNnc5WlhTSU1k
            QVNkWGF1blhhaWJIUTcvMG5SWjB2eTAKLS0tIC9xS2hrelJ6ZEM5N21VN2lleGgx
            WlVBVHhOWjBPRyt3WVhOQTdxb3F5ck0KHR4UOJEPutmzz8L0uY8HZD+oIvyGGA+K
            s2vEuqN+WfYd1ZidtmrRUOoNgIksA20QLxYoDL0ySWElmE+z5/XzEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESlZCaWZjYUVVaXBFZlBE
            TmoxUndpNzBSZXhpbGd2dTl1bmhoTEtFYkhBCnB4WWdjWEUxWXRPRG9xM3hNTGtw
            bFAzNWVFdFZLYk1OV1RCcTlLQ3JwRkkKLS0tIGNyYVdJM1RTVkRHaGtRMlE0aTVN
            UHBvMS9Ob09jQUxvWUFOdldwaW4reXMKlUqhTRKUUpM6CCz/hup8uXvexYQbapoP
            HfrQGD8N3CNcwELbbrytZsA5ICJCC69dWRxJrYaSgXPy0XRbzp2MIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T08:31:05Z"
    mac: ENC[AES256_GCM,data:A6cjgvuRK/UJ4SaDEMS3sBetg3ZXAsQ05CAYyoPWXKPb9mB0K8aYADo4gppcqEUR7qWYbaIwFMrk/uQvG2r7GRzFp11g5PvKXPEH+a1/8ZW1fgu/bqERNJvjO8ckfTWWEfG3c5vj6K0nBVGPoj8ZKGA71BPAFqsnv8bjS9BZM4Y=,iv:Ta55Jt03CUvP6DmqpwmrcagnbwNdvt2vmNYOAnX5RiA=,tag:sXW4H/FTK07ZxBYoYkdv3w==,type:str]
    version: 3.13.3
