apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy
    namespace: monitoring
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:Kn9T25CwN1F3EobNP/6hadXXY8f3t74RyxcsRj2D89Ktg0C+LeQLSsFpW3bl/yflHnEkdd3rZa6YZkmE,iv:nbPS4MDwjh1R82WebBYDLz5ODKiOU7LQy/c18NqLh30=,tag:/2jGu4bFkNpiJR1IN4/v6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUVlKOWdXR1RGT0dhUlVK
            amJ4MXdOOG52YjNBQitmdk81eDA4Q1Q2N2lJClNvdVlYZVdKUzlMOFFVd21GcS9z
            SnBlWnl4N3F0eFdzckRPYm1ZeXY1SDAKLS0tIEIrR21xZkdNV2lrcjc2eDZKU0xo
            UDlxc0lLTHpSS0xhMGNmSGlncGppOWsKdDsFUfq5O4u1UtoE8fyUY2YBq3deH+rw
            W05xkjpwMe/oXEs/bnFZDQcGFYBgIdTUuxgBgV0SbXmkCVw9tYOcCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSzl5eDVCcWRla3hrb2R2
            MHRTdUF6UHBmVHF2R0I4UXVFRENMeGpCcUV3ClZpS3JkczRYdEo2bk5KeXJYVVlp
            MU9UdFpQU0NGTHMwWmJNK2VaQ2NacWcKLS0tIG5tc2g2dytFMFI2dFo1YWZFQUJR
            eURMbHVnTTBCdGFzd0tyVUptSnR0QlUKLXUzI6w979LZzWbYrrxEZGmMf+TRtAe8
            yoQePBuXEKDSFy+2D+jZT09U8PkV930Qe5Wa9Mk6Zw3VDKO7g5Sscw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T08:31:04Z"
    mac: ENC[AES256_GCM,data:vAyCXNOr2001Zon1Z+0hGevUEGcmU1X66F2xIbcLheo0cIZ4I1oK6IjndehV1BkGaju0aXXyg5rLe1Tpa0kmdmogSL4cJqV/Wtj8cLaYD2ldWpdSxYCAxIhbkE7KRgSKhVmrOder+Cqn+i9mKVVKxEwxmHtFsv4rplD7EoSXlZw=,iv:2k3y8SEnNd4UjaZ5719tz3HCNNKKCInySnd8N2WQsPY=,tag:XwAHODoEZpjQFv7cFd1qHQ==,type:str]
    version: 3.13.3
