apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:62/FJI4=,iv:DwER3SYE4881AOO2mGf3yS1zfl8gV/fbxOeqxvkX7xw=,tag:f7dMyUOv6tPeZeAyys7hLg==,type:str]
    admin-password: ENC[AES256_GCM,data:S9uB9rYwdMyrgoGb5/6izwj5C/OJDdXAJNcshtMcI4CO6NGESpMdsuaj9SlrrOFZ,iv:eehZSnr/UD6PXjjmc09J5//alLrmX/OhSZeFDMJlNh4=,tag:Wa6T8/+Mt8TYj+ibx5Pg2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcVluamZNV0FUbEFhMUNO
            c0FvK28ydTRSK2RSdnB5cG9wV0tIZ08wRkRJCmtXb29vTUFicUZpeFJYS0I1eUN0
            RFFVWTBIOHcweEJiT1RMdDdGL0ExQzAKLS0tIEtJRzBYMTRlWUpVWFQvcDhzSGxT
            N1IrTUZSSmxybGtHcFV1SEUrZHBSWmMKkGCNoU9vPSx4kWxqLfnAhYAMs0NPP3py
            500ApF1l85mobjJEsKdkXI69J8/iIqFA/mX4bf5019TT8EmXyWTfAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nj2j4yjxq2ckjp2qqperd3mxnkmfak62vnyselafdrumzknzq4vqrsqkt0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVzJkd2xITUVRbFdqK3Bv
            angyOUt5MEFidkIzMm1nSnpTWjA1djQ3aUZBClFzSlN2VmpkY21Yc0FwZnBUSURz
            cHczYy9PWWxEVWdaTUZPRVoxQjBYQzQKLS0tIGRZUU9ENXRXRWNyZmFXaGUrby94
            ZnhmWDFlY2NVdUJlYWcwY1RHTm5oWTAKmfeEzzLYilvAdKYt7ZmMaKOlx2comsMe
            1tiKAs2clRoFEvUSN1ZHUP/5++s3uDkB/lvSfHTIbyJx+bNCAjVH8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fkgauddyappmru0m4nvwgv3fc7l3ekj83q3yh86kakm83y9pjf6qszpq9k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T08:31:02Z"
    mac: ENC[AES256_GCM,data:zPz3RlsQEYChZjnZSmPNaqynZgxQnfEvEMT1xJRKQxRwJfPABKlWQFKZVM5chRYPczWJw6hI70eSQ0+C3Gpdkxg8j0sdWslDVB6t2/Hq5lgIMf6K6GeY1XWbWTmiu9qbIwWMqzvxwPy1fs3mQ6Djw9lp22zP+8nasFoaieU6Fgc=,iv:AzRFdfS8eWBa8iE/9XsXntrBkIwl99nMplJhSInUKMc=,tag:7j0cAYzTeuXLUTmfBoPt3g==,type:str]
    version: 3.13.3
