apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - referencegrant.yaml
  - servicemonitor-cloudflared.yaml
  - servicemonitor-cert-manager.yaml
  - dashboard-notebook-api.yaml
  - platform-alerts.yaml
  - networkpolicy.yaml
generators:
  - ksops-generator.yaml
