apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app: cert-manager
      app.kubernetes.io/component: controller
  endpoints:
    - targetPort: 9402
      path: /metrics
      interval: 30s
